version: "3"
services:
  client:
    image: "richardsutiono12/multi-client"
    mem_limit: 128m #Kasi limit untuk RAM di AWS (kayaknya limit juga untuk server local sih, gk harus AWS)
    hostname: client
  server: #diganti jadi api juga bisa sepertinya
    image: "richardsutiono12/multi-server"
    mem_limit: 128m
    hostname: api #cara biar container lain bisa panggil container ini. Karena di default.conf kita sebut api, jadi di sini disebut api juga
    environment:
      - REDIS_HOST=$REDIS_HOST #Cek dari elastic cache dashboard -> clusternya -> Primary endpoint. Masukin di EBS environment (TANPA PORT nya)
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "richardsutiono12/multi-worker"
    mem_limit: 128m
    hostname: worker #Ini juga gk perlu
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "richardsutiono12/multi-nginx"
    mem_limit: 128m
    hostname: nginx #Ini harusnya gk perlu, soalnya kan nginx yang pakai container lain. Dia kan gk dipakai container lain, jadi sebenernya gk perlu 
    ports:
      - "80:80"