version: '3'
services:
  postgres:
    image: 'postgres:latest'
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password 
  redis:
    image: 'redis:latest'
  nginx:
    restart: unless-stopped
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - "3050:80" 
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev #Ini cuma untuk naruh nama file aja
      context: ./server #Untuk naruh path foldernya. Kalau pakai ., berarti foldernya ada di root (gk usah masuk ke subfolder gitu)
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:80"